name: Build and Deploy

on:
  push:
    branches: main
    
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
              
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install Project Dependencies
        run: npm ci
                
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli
        
      - name: Make output folder
        run: mkdir public
        
      - name: Build
        run: gatsby build
        
      - name: Gatsby Cache
        uses: jongwooo/gatsby-cache@v1.4.2
        with:
          branch: relese
          folder: public
        
      - name: Verify build
        run: ls -la public
    
